In [23]:
import pandas as pd
import numpy as np

In [24]:
df_Recruitment=pd.read_excel(r"../hire_to_retire_analytics.xlsx",sheet_name="Recruitment")
df_Recruitment.head()

,Req_ID,Candidate_ID,Employee_ID,Pipeline_Status,Vacancy_Start_Date,Hire_Date,Days_to_Fill,Sourcing_Channel,Sourcing_Cost,Cost_of_Vacancy,...,Skill_Score,Culture_Score,Potential_Score,LQI,True_LQI,Bias_Flag,Gender,Ethnicity,Age_Band,Education_Level
0,REQ_000001,CAND_000001,NaN,Rejected_Offer,NaT,NaT,113,Employee_Referral,1500,0,...,69.5,45.4,55.1,57.95,57.95,False,Female,Asian,41_50,Bachelors
1,REQ_000002,CAND_000002,NaN,Rejected_Offer,NaT,NaT,93,Agency,12000,0,...,51.0,30.8,63.9,48.81,48.81,False,Non_Binary,Asian,22_30,Bachelors
2,REQ_000003,CAND_000003,NaN,Rejected_Offer,NaT,NaT,113,Job_Board,2500,0,...,64.3,55.4,58.1,59.77,59.77,False,Male,Hispanic_Latino,31_40,Bachelors
3,REQ_000004,CAND_000004,EMP_000001,Hired,2018-01-01,2018-01-01,0,Employee_Referral,1500,0,...,78.1,77.7,59.7,72.46,72.46,False,Female,Other,31_40,High_School
4,REQ_000005,CAND_000005,EMP_000002,Hired,2018-01-01,2018-01-01,0,Job_Board,2500,0,...,63.2,70.5,48.5,60.98,60.98,False,Female,Hispanic_Latino,22_30,High_School

In [25]:
df_Recruitment_new=df_Recruitment.copy()

In [26]:
df_Recruitment_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 35714 entries, 0 to 35713
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Req_ID                  35714 non-null  str
 1   Candidate_ID            35714 non-null  str
 2   Employee_ID             25000 non-null  str
 3   Pipeline_Status         35714 non-null  str
 4   Vacancy_Start_Date      25000 non-null  datetime64[us]
 5   Hire_Date               25000 non-null  datetime64[us]
 6   Days_to_Fill            35714 non-null  int64
 7   Sourcing_Channel        35714 non-null  str
 8   Sourcing_Cost           35714 non-null  int64
 9   Cost_of_Vacancy         35714 non-null  int64
 10  Total_Acquisition_Cost  35714 non-null  int64
 11  Skill_Score             35714 non-null  float64
 12  Culture_Score           35714 non-null  float64
 13  Potential_Score         35714 non-null  float64
 14  LQI                     35714 non-null  float64
 15  True_LQI                35714 non-null  float64
 16  Bias_Flag               35714 non-null  bool
 17  Gender                  35714 non-null  str
 18  Ethnicity               35714 non-null  str
 19  Age_Band                35714 non-null  str
 20  Education_Level         35714 non-null  str
dtypes: bool(1), datetime64[us](2), float64(5), int64(4), str(9)
memory usage: 5.5 MB

In [27]:
df_Recruitment_new.shape

(35714, 21)

In [28]:
df_Recruitment_new.duplicated().sum()

np.int64(0)

In [29]:
df_Recruitment_new.isnull().sum()

Req_ID                        0
Candidate_ID                  0
Employee_ID               10714
Pipeline_Status               0
Vacancy_Start_Date        10714
Hire_Date                 10714
Days_to_Fill                  0
Sourcing_Channel              0
Sourcing_Cost                 0
Cost_of_Vacancy               0
Total_Acquisition_Cost        0
Skill_Score                   0
Culture_Score                 0
Potential_Score               0
LQI                           0
True_LQI                      0
Bias_Flag                     0
Gender                        0
Ethnicity                     0
Age_Band                      0
Education_Level               0
dtype: int64

In [30]:
df_Recruitment_new["Employee_ID"]=df_Recruitment_new["Employee_ID"].fillna("Unknown")

In [31]:
df_Recruitment_new["Hire_Date"]=df_Recruitment_new["Hire_Date"].ffill()

In [32]:
df_Recruitment_new["Vacancy_Start_Date"]=df_Recruitment_new["Vacancy_Start_Date"].ffill()

In [33]:
df_Recruitment_new["Vacancy_Start_Date"]=df_Recruitment_new["Vacancy_Start_Date"].bfill()

In [34]:
df_Recruitment_new["Hire_Date"]=df_Recruitment_new["Hire_Date"].bfill()

In [35]:
df_Recruitment_new.head(10)

,Req_ID,Candidate_ID,Employee_ID,Pipeline_Status,Vacancy_Start_Date,Hire_Date,Days_to_Fill,Sourcing_Channel,Sourcing_Cost,Cost_of_Vacancy,...,Skill_Score,Culture_Score,Potential_Score,LQI,True_LQI,Bias_Flag,Gender,Ethnicity,Age_Band,Education_Level
0,REQ_000001,CAND_000001,Unknown,Rejected_Offer,2018-01-01,2018-01-01,113,Employee_Referral,1500,0,...,69.5,45.4,55.1,57.95,57.95,False,Female,Asian,41_50,Bachelors
1,REQ_000002,CAND_000002,Unknown,Rejected_Offer,2018-01-01,2018-01-01,93,Agency,12000,0,...,51.0,30.8,63.9,48.81,48.81,False,Non_Binary,Asian,22_30,Bachelors
2,REQ_000003,CAND_000003,Unknown,Rejected_Offer,2018-01-01,2018-01-01,113,Job_Board,2500,0,...,64.3,55.4,58.1,59.77,59.77,False,Male,Hispanic_Latino,31_40,Bachelors
3,REQ_000004,CAND_000004,EMP_000001,Hired,2018-01-01,2018-01-01,0,Employee_Referral,1500,0,...,78.1,77.7,59.7,72.46,72.46,False,Female,Other,31_40,High_School
4,REQ_000005,CAND_000005,EMP_000002,Hired,2018-01-01,2018-01-01,0,Job_Board,2500,0,...,63.2,70.5,48.5,60.98,60.98,False,Female,Hispanic_Latino,22_30,High_School
5,REQ_000006,CAND_000006,EMP_000003,Hired,2018-01-01,2018-01-01,0,Employee_Referral,1500,0,...,68.7,73.9,72.7,71.46,71.46,False,Female,White,22_30,Bachelors
6,REQ_000007,CAND_000007,EMP_000004,Hired,2018-01-01,2018-01-01,0,Employee_Referral,1500,0,...,52.5,50.1,48.2,50.49,50.49,False,Non_Binary,White,41_50,Masters
7,REQ_000008,CAND_000008,EMP_000005,Hired,2018-01-01,2018-01-01,0,Agency,12000,0,...,68.7,80.1,61.2,69.87,69.87,False,Male,Hispanic_Latino,31_40,Bachelors
8,REQ_000009,CAND_000009,EMP_000006,Hired,2018-01-01,2018-01-01,0,Job_Board,2500,0,...,75.3,60.6,62.1,66.93,66.93,False,Female,Asian,22_30,Bachelors
9,REQ_000010,CAND_000010,EMP_000007,Hired,2018-01-01,2018-01-01,0,Internal_Transfer,800,0,...,61.6,59.9,48.6,57.19,57.19,False,Female,White,41_50,PhD

In [36]:
df_Recruitment_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 35714 entries, 0 to 35713
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Req_ID                  35714 non-null  str
 1   Candidate_ID            35714 non-null  str
 2   Employee_ID             35714 non-null  str
 3   Pipeline_Status         35714 non-null  str
 4   Vacancy_Start_Date      35714 non-null  datetime64[us]
 5   Hire_Date               35714 non-null  datetime64[us]
 6   Days_to_Fill            35714 non-null  int64
 7   Sourcing_Channel        35714 non-null  str
 8   Sourcing_Cost           35714 non-null  int64
 9   Cost_of_Vacancy         35714 non-null  int64
 10  Total_Acquisition_Cost  35714 non-null  int64
 11  Skill_Score             35714 non-null  float64
 12  Culture_Score           35714 non-null  float64
 13  Potential_Score         35714 non-null  float64
 14  LQI                     35714 non-null  float64
 15  True_LQI                35714 non-null  float64
 16  Bias_Flag               35714 non-null  bool
 17  Gender                  35714 non-null  str
 18  Ethnicity               35714 non-null  str
 19  Age_Band                35714 non-null  str
 20  Education_Level         35714 non-null  str
dtypes: bool(1), datetime64[us](2), float64(5), int64(4), str(9)
memory usage: 5.5 MB

In [37]:
for col in df_Recruitment_new.columns:
    if df_Recruitment_new[col].dtype=="object":
        df_Recruitment_new[col]=df_Recruitment_new[col].astype("string")

In [38]:
df_Recruitment_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 35714 entries, 0 to 35713
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Req_ID                  35714 non-null  str
 1   Candidate_ID            35714 non-null  str
 2   Employee_ID             35714 non-null  str
 3   Pipeline_Status         35714 non-null  str
 4   Vacancy_Start_Date      35714 non-null  datetime64[us]
 5   Hire_Date               35714 non-null  datetime64[us]
 6   Days_to_Fill            35714 non-null  int64
 7   Sourcing_Channel        35714 non-null  str
 8   Sourcing_Cost           35714 non-null  int64
 9   Cost_of_Vacancy         35714 non-null  int64
 10  Total_Acquisition_Cost  35714 non-null  int64
 11  Skill_Score             35714 non-null  float64
 12  Culture_Score           35714 non-null  float64
 13  Potential_Score         35714 non-null  float64
 14  LQI                     35714 non-null  float64
 15  True_LQI                35714 non-null  float64
 16  Bias_Flag               35714 non-null  bool
 17  Gender                  35714 non-null  str
 18  Ethnicity               35714 non-null  str
 19  Age_Band                35714 non-null  str
 20  Education_Level         35714 non-null  str
dtypes: bool(1), datetime64[us](2), float64(5), int64(4), str(9)
memory usage: 5.5 MB

In [39]:
df_Recruitment_new.describe()

,Vacancy_Start_Date,Hire_Date,Days_to_Fill,Sourcing_Cost,Cost_of_Vacancy,Total_Acquisition_Cost,Skill_Score,Culture_Score,Potential_Score,LQI,True_LQI
count,35714,35714,35714.000000,35714.000000,35714.000000,35714.000000,35714.000000,35714.000000,35714.000000,35714.000000,35714.000000
mean,2021-06-02 23:26:48.982471,2021-09-06 06:07:36.022848,95.821611,3525.541804,48047.047096,51572.588901,64.840441,59.985644,57.993266,61.329849,61.453582
min,2018-01-01 00:00:00,2018-01-01 00:00:00,0.000000,800.000000,0.000000,800.000000,3.600000,0.000000,0.000000,11.950000,11.950000
25%,2019-10-31 00:00:00,2020-02-05 00:00:00,87.000000,1500.000000,0.000000,4000.000000,54.700000,49.900000,47.700000,52.970000,53.120000
50%,2021-07-19 00:00:00,2021-10-24 00:00:00,98.000000,2500.000000,63360.000000,66640.000000,64.900000,59.900000,58.100000,61.350000,61.485000
75%,2023-01-27 00:00:00,2023-05-04 00:00:00,107.000000,3000.000000,74160.000000,77820.000000,75.100000,70.200000,68.100000,69.700000,69.840000
max,2024-10-22 00:00:00,2024-12-30 00:00:00,119.000000,12000.000000,85680.000000,97680.000000,100.000000,100.000000,100.000000,100.000000,100.000000
std,NaN,NaN,15.402081,3236.451574,32953.400082,33100.989240,14.930616,14.992324,15.121644,12.364882,12.357563

In [40]:
df_Recruitment_new.to_csv("../CleanedCSVs/df_Recruitment_new.csv",index=False)