In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [3]:
Employee_Master=pd.read_excel(r"../hire_to_retire_analytics.xlsx",sheet_name="Employee_Master")
Employee_Master.head()

,Employee_ID,Candidate_ID,Hire_Date,Department,Role,Base_Salary,Manager_ID,Manager_Effect,Is_Bad_Manager,Is_Biased_Manager,Gender,Ethnicity,Age_Band,Education_Level,Skill_Score,Culture_Score,Potential_Score,LQI
0,EMP_000001,CAND_000004,2018-01-01,Sales,Account_Executive,118000,MGR_0152,-0.0369,False,False,Female,Other,31_40,High_School,78.1,77.7,59.7,72.46
1,EMP_000002,CAND_000005,2018-01-01,Product,CPO,134000,MGR_0006,-0.0079,False,False,Female,Hispanic_Latino,22_30,High_School,63.2,70.5,48.5,60.98
2,EMP_000003,CAND_000006,2018-01-01,Marketing,Content_Strategist,104000,MGR_0343,-0.0537,False,True,Female,White,22_30,Bachelors,68.7,73.9,72.7,71.46
3,EMP_000004,CAND_000007,2018-01-01,Product,Principal_PM,127000,MGR_0316,-0.1400,True,False,Non_Binary,White,41_50,Masters,52.5,50.1,48.2,50.49
4,EMP_000005,CAND_000008,2018-01-01,Operations,Operations_Manager,94000,MGR_0373,-0.1075,True,False,Male,Hispanic_Latino,31_40,Bachelors,68.7,80.1,61.2,69.87

In [4]:
Employee_Master_new=Employee_Master.copy()

In [5]:
Employee_Master_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        25000 non-null  str
 1   Candidate_ID       25000 non-null  str
 2   Hire_Date          25000 non-null  datetime64[us]
 3   Department         25000 non-null  str
 4   Role               25000 non-null  str
 5   Base_Salary        25000 non-null  int64
 6   Manager_ID         25000 non-null  str
 7   Manager_Effect     25000 non-null  float64
 8   Is_Bad_Manager     25000 non-null  bool
 9   Is_Biased_Manager  25000 non-null  bool
 10  Gender             25000 non-null  str
 11  Ethnicity          25000 non-null  str
 12  Age_Band           25000 non-null  str
 13  Education_Level    25000 non-null  str
 14  Skill_Score        25000 non-null  float64
 15  Culture_Score      25000 non-null  float64
 16  Potential_Score    25000 non-null  float64
 17  LQI                25000 non-null  float64
dtypes: bool(2), datetime64[us](1), float64(5), int64(1), str(9)
memory usage: 3.1 MB

In [6]:
Employee_Master_new.describe()

,Hire_Date,Base_Salary,Manager_Effect,Skill_Score,Culture_Score,Potential_Score,LQI
count,25000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,2021-09-09 17:14:47.040000,118647.40000,0.004159,70.590284,64.631044,63.361396,66.633846
min,2018-01-01 00:00:00,69000.00000,-0.216600,20.900000,17.200000,17.300000,34.580000
25%,2020-02-12 00:00:00,98000.00000,-0.056900,61.800000,55.500000,54.400000,59.700000
50%,2021-11-01 00:00:00,114000.00000,0.013200,70.300000,64.400000,63.100000,66.030000
75%,2023-05-05 00:00:00,140000.00000,0.067300,79.000000,73.700000,72.100000,73.100000
max,2024-12-30 00:00:00,198000.00000,0.190100,100.000000,100.000000,100.000000,100.000000
std,NaN,24190.65937,0.081616,12.521776,13.450747,13.146003,9.848769

In [7]:
Employee_Master_new.shape

(25000, 18)

In [8]:
Employee_Master_new.isnull().sum()

Employee_ID          0
Candidate_ID         0
Hire_Date            0
Department           0
Role                 0
Base_Salary          0
Manager_ID           0
Manager_Effect       0
Is_Bad_Manager       0
Is_Biased_Manager    0
Gender               0
Ethnicity            0
Age_Band             0
Education_Level      0
Skill_Score          0
Culture_Score        0
Potential_Score      0
LQI                  0
dtype: int64

In [9]:
Employee_Master_new.duplicated().sum()

np.int64(0)

In [10]:
for col in Employee_Master_new.columns:
    if Employee_Master_new[col].dtype=="object":
        Employee_Master_new[col]=Employee_Master_new[col].astype("string")

In [11]:
Employee_Master_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        25000 non-null  str
 1   Candidate_ID       25000 non-null  str
 2   Hire_Date          25000 non-null  datetime64[us]
 3   Department         25000 non-null  str
 4   Role               25000 non-null  str
 5   Base_Salary        25000 non-null  int64
 6   Manager_ID         25000 non-null  str
 7   Manager_Effect     25000 non-null  float64
 8   Is_Bad_Manager     25000 non-null  bool
 9   Is_Biased_Manager  25000 non-null  bool
 10  Gender             25000 non-null  str
 11  Ethnicity          25000 non-null  str
 12  Age_Band           25000 non-null  str
 13  Education_Level    25000 non-null  str
 14  Skill_Score        25000 non-null  float64
 15  Culture_Score      25000 non-null  float64
 16  Potential_Score    25000 non-null  float64
 17  LQI                25000 non-null  float64
dtypes: bool(2), datetime64[us](1), float64(5), int64(1), str(9)
memory usage: 3.1 MB

In [12]:
Employee_Master_new.to_csv("../CleanedCSVs/Employee_Master_new.csv",index=False)